version: "3"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${JNA_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${JNA_MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
  api:
    build: ./server
    restart: always
    environment:
      - JNA_MONGO_PASSWORD=${JNA_MONGO_PASSWORD}
      - JNA_MONGO_USERNAME=${JNA_MONGO_USERNAME}
      - JNA_GOOGLE_CLIENTID=${JNA_GOOGLE_CLIENTID}
      - JNA_GOOGLE_CLIENTSECRET=${JNA_GOOGLE_CLIENTSECRET}
      - JNA_FACEBOOK_CLIENTID=${JNA_FACEBOOK_CLIENTID}
      - JNA_FACEBOOK_CLIENTSECRET=${JNA_FACEBOOK_CLIENTSECRET}
      - JNA_JWT_SIGNING_KEY=${JNA_JWT_SIGNING_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
  ui:
    build: ./client
    restart: always
    ports:
      - "80:3000"
      - "443:3000"
    depends_on:
      - api
